openapi: 3.0.0
info:
  title: 加班管理系统 - 身份认证 API
  description: 提供用户认证、会话管理等相关功能的 API
  version: 1.0.0

servers:
  - url: /api/v1
    description: 开发环境

components:
  schemas:
    UserCredentials:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          description: 用户名
        password:
          type: string
          description: 密码
          format: password

    AuthenticationToken:
      type: object
      properties:
        token:
          type: string
          description: JWT 令牌
        expiresAt:
          type: string
          format: date-time
          description: 令牌过期时间

    UserInfo:
      type: object
      properties:
        userId:
          type: string
          description: 用户ID
        username:
          type: string
          description: 用户名
        firstName:
          type: string
          description: 名字
        lastName:
          type: string
          description: 姓氏
        role:
          type: string
          enum: [WORKER, SUPERVISOR, MANAGER, CUSTOMER, SYSTEM_ADMIN]
          description: 用户角色
        permissions:
          type: array
          items:
            type: string
          description: 用户权限列表

    Error:
      type: object
      properties:
        code:
          type: string
          description: 错误代码
        message:
          type: string
          description: 错误信息

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/login:
    post:
      summary: 用户登录
      description: 验证用户凭证并返回认证令牌
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
      responses:
        '200':
          description: 登录成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationToken'
        '401':
          description: 认证失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/logout:
    post:
      summary: 用户登出
      description: 终止用户当前会话
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 登出成功
        '401':
          description: 未认证
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/token/refresh:
    post:
      summary: 刷新认证令牌
      description: 使用当前有效的令牌获取新的认证令牌
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 令牌刷新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationToken'
        '401':
          description: 令牌无效或已过期
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/me:
    get:
      summary: 获取当前用户信息
      description: 获取已认证用户的详细信息
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 成功获取用户信息
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '401':
          description: 未认证
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/password:
    put:
      summary: 修改密码
      description: 修改当前用户密码
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - currentPassword
                - newPassword
              properties:
                currentPassword:
                  type: string
                  format: password
                  description: 当前密码
                newPassword:
                  type: string
                  format: password
                  description: 新密码
      responses:
        '200':
          description: 密码修改成功
        '401':
          description: 当前密码验证失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 