export enum OvertimeRequestStatus {
  PENDING_SUPERVISOR = 'PENDING_SUPERVISOR',
  SUPERVISOR_APPROVED = 'SUPERVISOR_APPROVED',
  PENDING_MANAGER = 'PENDING_MANAGER',
  PENDING_CUSTOMER = 'PENDING_CUSTOMER',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED'
} 